export default function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');


    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    const jokes = [
        { id: 1, j: "Why don’t skeletons fight each other?", p: "They don’t have the guts." },
        { id: 2, j: "Why can’t your nose be 12 inches long?", p: "Because then it would be a foot." },
        { id: 3, j: "Why can’t a leopard hide?", p: "Because it’s always spotted." },
        { id: 4, j: "Why did the golfer bring two pairs of pants?", p: "In case he got a hole in one." },
        { id: 5, j: "Why did the student eat his homework?", p: "Because his teacher said it was a piece of cake." },
        { id: 6, j: "Why don’t scientists trust atoms?", p: "Because they make up everything." },
        { id: 7, j: "What did one wall say to the other?", p: "I’ll meet you at the corner." },
        { id: 8, j: "Why was the stadium so hot?", p: "All the fans left." },
        { id: 9, j: "Why did the kid bring a ladder to school?", p: "He wanted to go to high school." },
        { id: 10, j: "Why did the picture go to jail?", p: "Because it was framed." },
        { id: 11, j: "Why don’t graveyards ever get overcrowded?", p: "Because people are dying to get in." },
        { id: 12, j: "What do you call a factory that makes okay products?", p: "A satisfactory." },
        { id: 13, j: "Why don’t melons get married?", p: "Because they cantaloupe." },
        { id: 14, j: "Why did the computer go to the doctor?", p: "It caught a virus." },
        { id: 15, j: "Why did the math book look so sad?", p: "It had too many problems." },
        { id: 16, j: "Why did the scarecrow win an award?", p: "Because he was outstanding in his field." },
        { id: 17, j: "Why don’t seagulls fly over the bay?", p: "Because then they’d be bagels." },
        { id: 18, j: "Why did the clock get kicked out of class?", p: "It tocked too much." },
        { id: 19, j: "Why did the belt go to jail?", p: "For holding up a pair of pants." },
        { id: 20, j: "Why was the broom late?", p: "It overswept." },
        { id: 21, j: "Why did the cookie go to the doctor?", p: "Because it felt crummy." },
        { id: 22, j: "Why did the banana go to the doctor?", p: "Because it wasn’t peeling well." },
        { id: 23, j: "Why don’t eggs tell jokes?", p: "They’d crack each other up." },
        { id: 24, j: "Why did the skeleton go to the party alone?", p: "Because he had no body to go with him." },
        { id: 25, j: "Why did the barber win the race?", p: "Because he took a short cut." },
        { id: 26, j: "Why did the fish blush?", p: "Because it saw the ocean’s bottom." },
        { id: 27, j: "Why did the man put his money in the freezer?", p: "He wanted cold, hard cash." },
        { id: 28, j: "Why don’t ants ever get sick?", p: "Because they have tiny ant-bodies." },
        { id: 29, j: "Why can’t you trust stairs?", p: "They’re always up to something." },
        { id: 30, j: "Why do cows wear bells?", p: "Because their horns don’t work." },
        { id: 31, j: "Why did the tomato turn red?", p: "Because it saw the salad dressing." },
        { id: 32, j: "Why don’t oysters share?", p: "Because they’re shellfish." },
        { id: 33, j: "Why did the skeleton sit out the dance?", p: "He had no body to dance with." },
        { id: 34, j: "Why don’t some couples go to the gym?", p: "Because some relationships don’t work out." },
        { id: 35, j: "Why was the computer cold?", p: "It left its Windows open." },
        { id: 36, j: "Why did the music teacher go to jail?", p: "Because she got caught with too many sharp objects." },
        { id: 37, j: "Why do bees have sticky hair?", p: "Because they use honeycombs." },
        { id: 38, j: "Why did the golfer bring a spare shirt?", p: "In case he got a hole in one." },
        { id: 39, j: "Why did the bicycle fall over?", p: "Because it was two-tired." },
        { id: 40, j: "Why was the math teacher suspicious of prime numbers?", p: "They were acting odd." },
        { id: 41, j: "Why don’t teddy bears ever get hungry?", p: "Because they’re always stuffed." },
        { id: 42, j: "Why was the baseball stadium so windy?", p: "Because it was full of fans." },
        { id: 43, j: "Why was the computer late to work?", p: "It had a hard drive." },
        { id: 44, j: "Why did the phone go to therapy?", p: "Because it lost its contacts." },
        { id: 45, j: "Why did the grape stop in the middle of the road?", p: "Because it ran out of juice." },
        { id: 46, j: "Why was the skeleton always so calm?", p: "Because nothing got under his skin." },
        { id: 47, j: "Why don’t volcanoes ever get in trouble?", p: "Because they just erupt when they’re mad." },
        { id: 48, j: "Why don’t fish play basketball?", p: "They’re afraid of the net." },
        { id: 49, j: "Why did the astronaut break up with his girlfriend?", p: "He needed space." },
        { id: 50, j: "Why did the cow become an astronaut?", p: "So it could see the moooon." },
        { id: 51, j: "Why did the skeleton refuse to fight?", p: "He didn’t have the stomach for it." },
        { id: 52, j: "Why did the teacher wear sunglasses?", p: "Because her students were so bright." },
        { id: 53, j: "Why did the computer keep sneezing?", p: "It had a bad case of megabytes." },
        { id: 54, j: "Why did the fisherman bring a ladder?", p: "To catch a high tide." },
        { id: 55, j: "Why did the banker switch careers?", p: "He lost interest." },
        { id: 56, j: "Why did the gardener quit?", p: "Because his celery wasn’t high enough." },
        { id: 57, j: "Why did the music note go to school?", p: "To become a little sharper." },
        { id: 58, j: "Why did the baker stop making donuts?", p: "He got tired of the hole thing." },
        { id: 59, j: "Why did the light bulb fail school?", p: "Because it wasn’t too bright." },
        { id: 60, j: "Why did the fish always know how much it weighed?", p: "Because it had its own scales." },
        { id: 61, j: "Why was the belt such a good comedian?", p: "Because it always had people in stitches." },
        { id: 62, j: "Why did the man run around his bed?", p: "Because he was trying to catch up on his sleep." },
        { id: 63, j: "Why did the barber always win races?", p: "Because he knew all the short cuts." },
        { id: 64, j: "Why don’t bakers work in the dark?", p: "Because they need enough light to make the dough rise." },
        { id: 65, j: "Why was the ghost bad at lying?", p: "Because it was too transparent." },
        { id: 66, j: "Why did the pirate go to school?", p: "To improve his arrr-ticulation." },
        { id: 67, j: "Why was the cat sitting on the computer?", p: "It wanted to keep an eye on the mouse." },
        { id: 68, j: "Why did the broom apply for a job?", p: "It wanted to sweep into a new career." },
        { id: 69, j: "Why did the fish live in salt water?", p: "Because pepper made it sneeze." },
        { id: 70, j: "Why was the calendar always popular?", p: "Because it had so many dates." },
        { id: 71, j: "Why was the music note so polite?", p: "Because it always said, ‘Mi, mi, mi.’" },
        { id: 72, j: "Why did the crab never share?", p: "Because it was a little shellfish." },
        { id: 73, j: "Why did the frog take the bus to work?", p: "Because his car got toad away." },
        { id: 74, j: "Why did the baseball player bring a rope?", p: "To tie the score." },
        { id: 75, j: "Why did the skeleton always win races?", p: "Because he was ahead of the rest." },
        { id: 76, j: "Why did the pancake go to the doctor?", p: "It was feeling a little flat." },
        { id: 77, j: "Why did the ghost go to school?", p: "To learn how to be a little brighter." },
        { id: 78, j: "Why did the chicken join the band?", p: "Because it had drumsticks." },
        { id: 79, j: "Why don’t clouds ever get lost?", p: "Because they always follow the wind." },
        { id: 80, j: "Why did the pencil get an award?", p: "Because it was sharp." },
        { id: 81, j: "Why was the calendar nervous?", p: "Because its days were numbered." },
        { id: 82, j: "Why did the snowman look in the mirror?", p: "To see his snow-face." },
        { id: 83, j: "Why did the dog sit in the shade?", p: "Because he didn’t want to be a hot dog." },
        { id: 84, j: "Why was the computer so smart?", p: "It listened to its motherboard." },
        { id: 85, j: "Why did the firefly get bad grades?", p: "Because it wasn’t very bright." },
        { id: 86, j: "Why was the cat so good at video games?", p: "Because it had nine lives." },
        { id: 87, j: "Why did the fish get good grades?", p: "Because it was an excellent swimmer." },
        { id: 88, j: "Why was the broom excited?", p: "Because it was going on a sweepstake." },
        { id: 89, j: "Why did the cow go to space?", p: "To see the Milky Way." },
        { id: 90, j: "Why did the farmer win an award?", p: "Because he was out standing in his field." },
        { id: 91, j: "Why was the light bulb always happy?", p: "Because it brightened everyone’s day." },
        { id: 92, j: "Why did the squirrel take the elevator?", p: "Because it was too tired to take the stairs." },
        { id: 93, j: "Why was the dog a great musician?", p: "Because it had perfect pitch." },
        { id: 94, j: "Why did the frog bring a suitcase?", p: "Because it was going on a jump trip." },
        { id: 95, j: "Why did the music class need a ladder?", p: "To reach the high notes." },
        { id: 96, j: "Why was the skeleton afraid of the storm?", p: "Because it didn’t have a backbone." },
        { id: 97, j: "Why did the banana go to school?", p: "Because it wanted to be a smart fruit." },
        { id: 98, j: "Why did the snowman call his dog Frost?", p: "Because Frost bites." },
        { id: 99, j: "Why did the mushroom get invited to the party?", p: "Because he was a fun-gi." },
        { id: 100, j: "Why did the dog chase his tail?", p: "Because he was trying to make ends meet." }
];

    res.status(200).json(jokes); 
}