export default function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');


    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    const jokes = [
        { "id": 1, "j": "Why don’t skeletons fight each other?", "p": "They don’t have the guts." },
        { "id": 2, "j": "Why can’t your nose be 12 inches long?", "p": "Because then it would be a foot." },
        { "id": 3, "j": "Why can’t a leopard hide?", "p": "Because it’s always spotted." },
        { "id": 4, "j": "Why did the golfer bring an extra pencil?", "p": "In case he made a draw." },
        { "id": 5, "j": "Why did the student eat his homework?", "p": "Because his teacher said it was a piece of cake." },
        { "id": 6, "j": "Why don’t scientists trust atoms?", "p": "Because they make up everything." },
        { "id": 7, "j": "What did one wall say to the other?", "p": "I’ll meet you at the corner." },
        { "id": 8, "j": "Why was the stadium so hot?", "p": "All the fans left." },
        { "id": 9, "j": "Why did the kid bring a ladder to school?", "p": "He wanted to go to high school." },
        { "id": 10, "j": "Why did the picture go to jail?", "p": "Because it was framed." },
        { "id": 11, "j": "Why don’t graveyards ever get overcrowded?", "p": "Because people are dying to get in." },
        { "id": 12, "j": "What do you call a factory that makes okay products?", "p": "A satisfactory." },
        { "id": 13, "j": "Why don’t melons get married?", "p": "Because they cantaloupe." },
        { "id": 14, "j": "Why did the computer go to the doctor?", "p": "It caught a virus." },
        { "id": 15, "j": "Why did the math book look so sad?", "p": "It had too many problems." },
        { "id": 16, "j": "Why did the scarecrow become a successful neurosurgeon?", "p": "Because he was outstanding in his field of brains." },
        { "id": 17, "j": "Why don’t seagulls fly over the bay?", "p": "Because then they’d be bagels." },
        { "id": 18, "j": "Why did the clock get kicked out of class?", "p": "It tocked too much." },
        { "id": 19, "j": "Why did the belt go to jail?", "p": "For holding up a pair of pants." },
        { "id": 20, "j": "Why was the broom late?", "p": "It overswept." },
        { "id": 21, "j": "Why did the cookie go to the doctor?", "p": "Because it felt crummy." },
        { "id": 22, "j": "Why did the banana go to the doctor?", "p": "Because it wasn’t peeling well." },
        { "id": 23, "j": "Why don’t eggs tell jokes?", "p": "They’d crack each other up." },
        { "id": 24, "j": "Why don’t skeletons ever use cell phones?", "p": "Because they’d rather use their skulls." },
        { "id": 25, "j": "Why did the barber win the race?", "p": "Because he took a short cut." },
        { "id": 26, "j": "Why did the fish blush?", "p": "Because it saw the ocean’s bottom." },
        { "id": 27, "j": "Why did the man put his money in the freezer?", "p": "He wanted cold, hard cash." },
        { "id": 28, "j": "Why don’t ants ever get sick?", "p": "Because they have tiny ant-bodies." },
        { "id": 29, "j": "Why can’t you trust stairs?", "p": "They’re always up to something." },
        { "id": 30, "j": "Why do cows wear bells?", "p": "Because their horns don’t work." },
        { "id": 31, "j": "Why did the tomato go out with a prune?", "p": "Because it couldn’t find a date." },
        { "id": 32, "j": "Why don’t oysters share?", "p": "Because they’re shellfish." },
        { "id": 33, "j": "Why don’t skeletons ever get sunburned?", "p": "Because they’ve got no skin in the game." },
        { "id": 34, "j": "Why don’t some couples go to the gym?", "p": "Because some relationships don’t work out." },
        { "id": 35, "j": "Why was the computer cold?", "p": "It left its Windows open." },
        { "id": 36, "j": "Why did the music teacher go to jail?", "p": "Because she got caught with too many sharp objects." },
        { "id": 37, "j": "Why do bees have sticky hair?", "p": "Because they use honeycombs." },
        { "id": 38, "j": "Why did the golfer wear two hats?", "p": "In case he got a birdie on top." },
        { "id": 39, "j": "Why did the bicycle fall over?", "p": "Because it was two-tired." },
        { "id": 40, "j": "Why was the math teacher suspicious of prime numbers?", "p": "They were acting odd." },
        { "id": 41, "j": "Why don’t teddy bears ever get hungry?", "p": "Because they’re always stuffed." },
        { "id": 42, "j": "Why was the baseball stadium so windy?", "p": "Because it was full of fans." },
        { "id": 43, "j": "Why was the computer late to work?", "p": "It had a hard drive." },
        { "id": 44, "j": "Why did the phone go to therapy?", "p": "Because it lost its contacts." },
        { "id": 45, "j": "Why did the grape stop in the middle of the road?", "p": "Because it ran out of juice." },
        { "id": 46, "j": "Why was the skeleton always so calm?", "p": "Because nothing got under his skin." },
        { "id": 47, "j": "Why don’t volcanoes ever get in trouble?", "p": "Because they just erupt when they’re mad." },
        { "id": 48, "j": "Why don’t fish play basketball?", "p": "They’re afraid of the net." },
        { "id": 49, "j": "Why did the astronaut break up with his girlfriend?", "p": "He needed space." },
        { "id": 50, "j": "Why did the cow become an astronaut?", "p": "So it could see the moooon." },
        { "id": 51, "j": "Why did the skeleton refuse to fight?", "p": "He didn’t have the stomach for it." },
        { "id": 52, "j": "Why did the teacher wear sunglasses?", "p": "Because her students were so bright." },
        { "id": 53, "j": "Why did the computer keep sneezing?", "p": "It had a bad case of megabytes." },
        { "id": 54, "j": "Why did the fisherman bring a ladder?", "p": "To catch a high tide." },
        { "id": 55, "j": "Why did the banker switch careers?", "p": "He lost interest." },
        { "id": 56, "j": "Why did the gardener quit?", "p": "Because his celery wasn’t high enough." },
        { "id": 57, "j": "Why did the music note go to school?", "p": "To become a little sharper." },
        { "id": 58, "j": "Why did the baker stop making donuts?", "p": "He got tired of the hole thing." },
        { "id": 59, "j": "Why did the light bulb fail school?", "p": "Because it wasn’t too bright." },
        { "id": 60, "j": "Why did the fish always know how much it weighed?", "p": "Because it had its own scales." },
        { "id": 61, "j": "Why was the belt such a good comedian?", "p": "Because it always had people in stitches." },
        { "id": 62, "j": "Why did the man run around his bed?", "p": "Because he was trying to catch up on his sleep." },
        { "id": 63, "j": "Why did the barber always win races?", "p": "Because he knew all the short cuts." },
        { "id": 64, "j": "Why don’t bakers work in the dark?", "p": "Because they need enough light to make the dough rise." },
        { "id": 65, "j": "Why was the ghost bad at lying?", "p": "Because it was too transparent." },
        { "id": 66, "j": "Why did the pirate go to school?", "p": "To improve his arrr-ticulation." },
        { "id": 67, "j": "Why don’t cats play poker in the jungle?", "p": "Too many cheetahs." },
        { "id": 68, "j": "Why did the broom apply for a job?", "p": "It wanted to sweep into a new career." },
        { "id": 69, "j": "Why did the fish live in salt water?", "p": "Because pepper made it sneeze." },
        { "id": 70, "j": "Why was the calendar always popular?", "p": "Because it had so many dates." },
        { "id": 71, "j": "Why don’t calendars argue?", "p": "Because their days are numbered." },
        { "id": 72, "j": "Why did the crab never share?", "p": "Because it was a little shellfish." },
        { "id": 73, "j": "Why did the frog take the bus to work?", "p": "Because his car got toad away." },
        { "id": 74, "j": "Why did the baseball player bring a rope?", "p": "To tie the score." },
        { "id": 75, "j": "Why did the skeleton always win races?", "p": "Because he was ahead of the rest." },
        { "id": 76, "j": "Why did the pancake go to the doctor?", "p": "It was feeling a little flat." },
        { "id": 77, "j": "Why did the ghost become a cheerleader?", "p": "Because it had a lot of spirit." },
        { "id": 78, "j": "Why did the chicken join the band?", "p": "Because it had drumsticks." },
        { "id": 79, "j": "Why don’t clouds ever get lost?", "p": "Because they always follow the wind." },
        { "id": 80, "j": "Why did the pencil get an award?", "p": "Because it was sharp." },
        { "id": 81, "j": "Why was the calendar nervous?", "p": "Because its days were numbered." },
        { "id": 82, "j": "Why don’t snowmen ever argue?", "p": "Because they just let things slide." },
        { "id": 83, "j": "Why did the dog sit in the shade?", "p": "Because he didn’t want to be a hot dog." },
        { "id": 84, "j": "Why was the computer so smart?", "p": "It listened to its motherboard." },
        { "id": 85, "j": "Why did the firefly get bad grades?", "p": "Because it wasn’t very bright." },
        { "id": 86, "j": "Why was the cat so good at video games?", "p": "Because it had nine lives." },
        { "id": 87, "j": "Why did the fish get good grades?", "p": "Because it was an excellent swimmer." },
        { "id": 88, "j": "Why was the broom excited?", "p": "Because it was going on a sweepstake." },
        { "id": 89, "j": "Why did the cow go to space?", "p": "To see the Milky Way." },
        { "id": 90, "j": "Why did the farmer ride his tractor to school?", "p": "Because he wanted a little field trip." },
        { "id": 91, "j": "Why was the light bulb always happy?", "p": "Because it brightened everyone’s day." },
        { "id": 92, "j": "Why did the squirrel take the elevator?", "p": "Because it was too tired to take the stairs." },
        { "id": 93, "j": "Why was the dog a great musician?", "p": "Because it had perfect pitch." },
        { "id": 94, "j": "Why don’t frogs ever forget their homework?", "p": "Because they always ribbit down." },
        { "id": 95, "j": "Why did the music class need a ladder?", "p": "To reach the high notes." },
        { "id": 96, "j": "Why was the skeleton afraid of the storm?", "p": "Because it didn’t have a backbone." },
        { "id": 97, "j": "Why did the banana go to school?", "p": "Because it wanted to be a smart fruit." },
        { "id": 98, "j": "Why don’t snowmen ever get into arguments?", "p": "Because they just give each other the cold shoulder." },
        { "id": 99, "j": "Why did the mushroom get invited to the party?", "p": "Because he was a fun-gi." },
        { "id": 100, "j": "Why did the dog chase his tail?", "p": "Because he was trying to make ends meet." },
        { "id": 101, "j": "Why did the astronaut bring a pencil?", "p": "Because it wanted to draw space." },
        { "id": 102, "j": "Why did the bicycle go to bed early?", "p": "Because it was two-tired." },
        { "id": 103, "j": "Why don’t ghosts like rain?", "p": "Because it dampens their spirits." },
        { "id": 104, "j": "Why was the math book happy?", "p": "Because it had so many solutions." },
        { "id": 105, "j": "Why did the chicken join a rock band?", "p": "Because it had the drumsticks." },
        { "id": 106, "j": "Why did the bee get married?", "p": "Because it found its honey." },
        { "id": 107, "j": "Why was the computer’s belly full?", "p": "It ate too many cookies." },
        { "id": 108, "j": "Why was the broom so tired?", "p": "Because it had swept all day." },
        { "id": 109, "j": "Why did the book go to the hospital?", "p": "Because it broke its spine." },
        { "id": 110, "j": "Why did the orange stop?", "p": "Because it ran out of juice." },
        { "id": 111, "j": "Why did the duck get sent to the principal?", "p": "Because it was quacking jokes in class." },
        { "id": 112, "j": "Why don’t skeletons ever get mad?", "p": "Because nothing gets under their skin." },
        { "id": 113, "j": "Why did the scarecrow eat lunch alone?", "p": "Because he was out standing in his field." },
        { "id": 114, "j": "Why was the music class so noisy?", "p": "Because they had too many notes." },
        { "id": 115, "j": "Why did the mushroom always get invited out?", "p": "Because he was a real fun-gi." },
        { "id": 116, "j": "Why was the rope always stressed?", "p": "Because it was getting tied up in knots." },
        { "id": 117, "j": "Why did the paper always win?", "p": "Because it was tear-able." },
        { "id": 118, "j": "Why did the fish cross the ocean?", "p": "To get to the other tide." },
        { "id": 119, "j": "Why did the baker go broke?", "p": "Because he kept working for peanuts." },
        { "id": 120, "j": "Why don’t robots get tired?", "p": "Because they recharge at night." },
        { "id": 121, "j": "Why was the cat bad at school?", "p": "Because it kept playing hooky." },
        { "id": 122, "j": "Why did the pencil go on vacation?", "p": "Because it needed to get away from all the pressure." },
        { "id": 123, "j": "Why did the teacher love the chalkboard?", "p": "Because it was drawn to it." },
        { "id": 124, "j": "Why did the phone sit on the couch?", "p": "Because it lost its contacts." },
        { "id": 125, "j": "Why don’t calendars argue?", "p": "Because their days are numbered." },
        { "id": 126, "j": "Why did the snowman take a nap?", "p": "Because he was snow tired." },
        { "id": 127, "j": "Why did the cow go to music class?", "p": "To learn how to moo-sic." },
        { "id": 128, "j": "Why don’t spiders go to school?", "p": "Because they learn everything on the web." },
        { "id": 129, "j": "Why did the grape get stepped on?", "p": "Because it didn’t pay attention in the crush." },
        { "id": 130, "j": "Why was the broom always happy?", "p": "Because it swept all its problems away." },
        { "id": 131, "j": "Why did the chicken go to the library?", "p": "To check out a book." },
        { "id": 132, "j": "Why did the bell go to the doctor?", "p": "Because it had a ringing in its ears." },
        { "id": 133, "j": "Why did the pencil cross the road?", "p": "To draw attention." },
        { "id": 134, "j": "Why did the dog sit in class?", "p": "Because it was a student’s best friend." },
        { "id": 135, "j": "Why did the barber talk so much?", "p": "Because he loved cutting in." },
        { "id": 136, "j": "Why did the moon skip dinner?", "p": "Because it was already full." },
        { "id": 137, "j": "Why did the corn stalk tell jokes?", "p": "Because it was all ears." },
        { "id": 138, "j": "Why did the ladder feel lonely?", "p": "Because it was always being stepped on." },
        { "id": 139, "j": "Why was the lamp a good listener?", "p": "Because it was very bright." },
        { "id": 140, "j": "Why don’t elephants use computers?", "p": "Because they’re afraid of the mouse." },
        { "id": 141, "j": "Why did the gardener plant a light bulb?", "p": "Because he wanted to grow a power plant." },
        { "id": 142, "j": "Why did the banana get promoted?", "p": "Because it split its work evenly." },
        { "id": 143, "j": "Why did the cookie cry?", "p": "Because its mom was a wafer so long." },
        { "id": 144, "j": "Why did the skeleton go surfing?", "p": "Because it wanted some vitamin sea." },
        { "id": 145, "j": "Why don’t snowmen ever gossip?", "p": "Because they don’t want to stir up a snowstorm." },
        { "id": 146, "j": "Why was the balloon so good at school?", "p": "Because it always rose to the occasion." },
        { "id": 147, "j": "Why did the kangaroo stop drinking coffee?", "p": "Because it made it too jumpy." },
        { "id": 148, "j": "Why did the fish go to Hollywood?", "p": "Because it wanted to be a starfish." },
        { "id": 149, "j": "Why did the carrot get embarrassed?", "p": "Because it met a hot potato." },
        { "id": 150, "j": "Why did the skeleton bring a ladder to the bar?", "p": "Because it wanted to go to the high spirits." }
];

    res.status(200).json(jokes); 
}